// students.js
export const Students = [
  {
    id: 1,
    firstName: "Juan",
    lastName: "Dela Cruz",
    studentNumber: "2025-001",
    section: "A1",
    course: "BS Computer Science",
    position: "Class Rep",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    firstName: "Maria",
    lastName: "Santos",
    studentNumber: "2025-002",
    section: "A1",
    course: "BS Information Technology",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    firstName: "Pedro",
    lastName: "Reyes",
    studentNumber: "2025-003",
    section: "B1",
    course: "BS Computer Engineering",
    position: "Assistant Rep",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    firstName: "Ana",
    lastName: "Lopez",
    studentNumber: "2025-004",
    section: "B1",
    course: "BS Information Systems",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    firstName: "Carlos",
    lastName: "Garcia",
    studentNumber: "2025-005",
    section: "C1",
    course: "BS Electronics Engineering",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    firstName: "Luisa",
    lastName: "Martinez",
    studentNumber: "2025-006",
    section: "C1",
    course: "BS Computer Science",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    firstName: "Ramon",
    lastName: "Torres",
    studentNumber: "2025-007",
    section: "D1",
    course: "BS Information Technology",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    firstName: "Isabel",
    lastName: "Fernandez",
    studentNumber: "2025-008",
    section: "D1",
    course: "BS Computer Engineering",
    position: "Class Rep",
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
  },
];
