// students.js
export const Students = [
  {
    id: 1,
    fullName: {
      fname: "Juan",
      lname: "Dela Cruz",
      mname: "Ramos",
      suffix: "",
      postnominal: "MIT",
    },
    studentNumber: "2025-001",
    section: "A1",
    try: "testing",
    course: "BS Computer Science",
    position: "Class Rep",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    fullName: {
      fname: "Maria",
      lname: "Santos",
      mname: "Luisa",
      suffix: "",
      postnominal: "Cum Laude",
    },
    studentNumber: "2025-002",
    section: "A1",
    try: "testing",
    course: "BS Information Technology",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    fullName: {
      fname: "Pedro",
      lname: "Reyes",
      mname: "Domingo",
      suffix: "Jr.",
      postnominal: "",
    },
    studentNumber: "2025-003",
    section: "B1",
    try: "testing",
    course: "BS Computer Engineering",
    position: "Assistant Rep",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    fullName: {
      fname: "Ana",
      lname: "Lopez",
      mname: "Cruz",
      suffix: "",
      postnominal: "Dean’s Lister",
    },
    studentNumber: "2025-004",
    section: "B1",
    try: "testing",
    course: "BS Information Systems",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    fullName: {
      fname: "Carlos",
      lname: "Garcia",
      mname: "Manuel",
      suffix: "III",
      postnominal: "",
    },
    studentNumber: "2025-005",
    section: "C1",
    try: "testing",
    course: "BS Electronics Engineering",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    fullName: {
      fname: "Luisa",
      lname: "Martinez",
      mname: "Torres",
      suffix: "",
      postnominal: "MSc",
    },
    studentNumber: "2025-006",
    section: "C1",
    try: "testing",
    course: "BS Computer Science",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    fullName: {
      fname: "Ramon",
      lname: "Torres",
      mname: "Miguel",
      suffix: "Sr.",
      postnominal: "",
    },
    studentNumber: "2025-007",
    section: "D1",
    try: "testing",
    course: "BS Information Technology",
    position: "",
    profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    fullName: {
      fname: "Isabel",
      lname: "Fernandez",
      mname: "Del Rosario",
      suffix: "",
      postnominal: "PhD",
    },
    studentNumber: "2025-008",
    section: "D1",
    try: "testing",
    course: "BS Computer Engineering",
    position: "Class Rep",
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
  },
];
