import Avatar from "../../../assets/male.jpg";
import Avatar1 from "../../../assets/male1.jpg";
import Avatar2 from "../../../assets/male2.jpg";
import Avatar3 from "../../../assets/male3.jpeg";
import Avatar4 from "../../../assets/male4.jpg";
import Avatar5 from "../../../assets/male5.jpg";
import Avatar6 from "../../../assets/female6.jpg";
import Avatar7 from "../../../assets/female7.jpg";
import Avatar8 from "../../../assets/female1.jpg";
import Avatar9 from "../../../assets/female2.jpg";

export const Employee = [
  {
    id: "SCGT-001",
    fullName: {
      fname: "Juan",
      lname: "Dela Cruz",
      mname: "Ramos",
      suffix: "Jr.",
      title: "Dr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "Mabini Extension",
    },
    position: "Medical Technologist 1",
    department: "Laboratory",
    dob: "2005-12-24",
    mobile: "9273526159",
    email: "juan@gmail.com",
    profileImage: Avatar,
    contactInfo: {
      fullName: {
        fname: "Maria",
        lname: "Santos",
        mname: "Luisa",
        suffix: "",
        title: "Ms.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "Mabini Extension",
      },
      pn: "9273526159",
    },
  },
  {
    id: "SCGT-002",
    fullName: {
      fname: "Pedro",
      lname: "Reyes",
      mname: "Domingo",
      suffix: "",
      title: "Mr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "San Jose",
    },
    position: "Lab Assistant",
    department: "Laboratory",
    dob: "2004-07-15",
    mobile: "9273526160",
    email: "pedro@gmail.com",
    profileImage: Avatar1,
    contactInfo: {
      fullName: {
        fname: "Luisa",
        lname: "Martinez",
        mname: "Torres",
        suffix: "",
        title: "Ms.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "San Jose",
      },
      pn: "9273526160",
    },
  },
  {
    id: "SCGT-003",
    fullName: {
      fname: "Ana",
      lname: "Lopez",
      mname: "Cruz",
      suffix: "",
      title: "Dr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "Mabini Extension",
    },
    position: "Medical Technologist 2",
    department: "Laboratory",
    dob: "2005-03-10",
    mobile: "9273526161",
    email: "ana@gmail.com",
    profileImage: Avatar2,
    contactInfo: {
      fullName: {
        fname: "Pedro",
        lname: "Reyes",
        mname: "Domingo",
        suffix: "",
        title: "Mr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "Mabini Extension",
      },
      pn: "9273526161",
    },
  },
  {
    id: "SCGT-004",
    fullName: {
      fname: "Carlos",
      lname: "Garcia",
      mname: "Manuel",
      suffix: "",
      title: "Mr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "San Antonio",
    },
    position: "Intern",
    department: "Laboratory",
    dob: "2006-01-22",
    mobile: "9273526162",
    email: "carlos@gmail.com",
    profileImage: Avatar3,
    contactInfo: {
      fullName: {
        fname: "Ana",
        lname: "Lopez",
        mname: "Cruz",
        suffix: "",
        title: "Dr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "San Antonio",
      },
      pn: "9273526162",
    },
  },
  {
    id: "SCGT-005",
    fullName: {
      fname: "Maria",
      lname: "Santos",
      mname: "Luisa",
      suffix: "",
      title: "Ms.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "Mabini Extension",
    },
    position: "Lab Assistant",
    department: "Laboratory",
    dob: "2005-11-30",
    mobile: "9273526163",
    email: "maria@gmail.com",
    profileImage: Avatar4,
    contactInfo: {
      fullName: {
        fname: "Carlos",
        lname: "Garcia",
        mname: "Manuel",
        suffix: "",
        title: "Mr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "Mabini Extension",
      },
      pn: "9273526163",
    },
  },
  {
    id: "SCGT-006",
    fullName: {
      fname: "Luis",
      lname: "Martinez",
      mname: "Torres",
      suffix: "",
      title: "Mr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "San Jose",
    },
    position: "Medical Technologist 3",
    department: "Laboratory",
    dob: "2004-06-18",
    mobile: "9273526164",
    email: "luis@gmail.com",
    profileImage: Avatar5,
    contactInfo: {
      fullName: {
        fname: "Maria",
        lname: "Santos",
        mname: "Luisa",
        suffix: "",
        title: "Ms.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "San Jose",
      },
      pn: "9273526164",
    },
  },
  {
    id: "SCGT-007",
    fullName: {
      fname: "Isabel",
      lname: "Fernandez",
      mname: "Del Rosario",
      suffix: "",
      title: "Dr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "San Antonio",
    },
    position: "Intern",
    department: "Laboratory",
    dob: "2005-09-12",
    mobile: "9273526165",
    email: "isabel@gmail.com",
    profileImage: Avatar6,
    contactInfo: {
      fullName: {
        fname: "Luis",
        lname: "Martinez",
        mname: "Torres",
        suffix: "",
        title: "Mr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "San Antonio",
      },
      pn: "9273526165",
    },
  },
  {
    id: "SCGT-008",
    fullName: {
      fname: "Ramon",
      lname: "Torres",
      mname: "Miguel",
      suffix: "",
      title: "Mr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "Mabini Extension",
    },
    position: "Medical Technologist 4",
    department: "Laboratory",
    dob: "2004-04-05",
    mobile: "9273526166",
    email: "ramon@gmail.com",
    profileImage: Avatar7,
    contactInfo: {
      fullName: {
        fname: "Isabel",
        lname: "Fernandez",
        mname: "Del Rosario",
        suffix: "",
        title: "Dr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "Mabini Extension",
      },
      pn: "9273526166",
    },
  },
  {
    id: "SCGT-009",
    fullName: {
      fname: "Pedro",
      lname: "Reyes",
      mname: "Domingo",
      suffix: "",
      title: "Mr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "San Jose",
    },
    position: "Lab Assistant",
    department: "Laboratory",
    dob: "2005-01-19",
    mobile: "9273526167",
    email: "pedro2@gmail.com",
    profileImage: Avatar8,
    contactInfo: {
      fullName: {
        fname: "Ramon",
        lname: "Torres",
        mname: "Miguel",
        suffix: "",
        title: "Mr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "San Jose",
      },
      pn: "9273526167",
    },
  },
  {
    id: "SCGT-010",
    fullName: {
      fname: "Ana",
      lname: "Lopez",
      mname: "Cruz",
      suffix: "",
      title: "Dr.",
    },
    address: {
      region: "REGION III (CENTRAL LUZON)",
      province: "NUEVA ECIJA",
      city: "CABANATUAN CITY",
      barangay: "San Antonio",
    },
    position: "Medical Technologist 5",
    department: "Laboratory",
    dob: "2004-02-28",
    mobile: "9273526168",
    email: "ana2@gmail.com",
    profileImage: Avatar9,
    contactInfo: {
      fullName: {
        fname: "Pedro",
        lname: "Reyes",
        mname: "Domingo",
        suffix: "",
        title: "Mr.",
      },
      address: {
        region: "REGION III (CENTRAL LUZON)",
        province: "NUEVA ECIJA",
        city: "CABANATUAN CITY",
        barangay: "San Antonio",
      },
      pn: "9273526168",
    },
  },
];
