import { MDBCol, MDBRow } from "mdbreact";
import React, { useEffect, useState } from "react";
import { fullName, getAge } from "../../../services/utilities";
import { useSelector } from "react-redux";

const RequestOutSource = () => {
  const { auth } = useSelector(({ auth }) => auth),
    [request, setRequest] = useState({});

  useEffect(() => {
    const _request = JSON.parse(localStorage.getItem("outsource_request"));

    setRequest(_request);
  }, []);

  const { deal = {}, outsources = [], sentOut = {} } = request || {};
  const { customerId = {}, category, ssx } = deal;
  return (
    <div
      className="mx-1"
      style={{
        width: "630px",
        cursor: "default",
        fontFamily: "Helvetica, sans-serif",
        letterSpacing: "-0.5px",
        fontSize: "16px !important",
      }}
    >
      <MDBRow>
        <MDBCol>
          <div style={{ border: "2px solid black" }} className="mt-2">
            <div
              style={{
                background: "black",
                height: "1.4rem",
              }}
              className="d-flex align-items-center justify-content-center"
            >
              <h5
                className="text-white"
                style={{ fontSize: "1rem", marginTop: "0.6rem" }}
              >
                OUTSOURCE REQUEST FORM
              </h5>
            </div>
            <div
              className="d-flex align-items-center  justify-content-between p-1"
              style={{ borderBottom: "1px solid black", height: "1.7rem" }}
            >
              <div className="d-flex align-items-center mt-1">
                <h6 className="font-weight-bold mr-1">Patient Name:</h6>
                <h6>{fullName(customerId?.fullName)}</h6>
              </div>
              <div>
                <div className="d-flex align-items-center mt-1">
                  <h6 className="font-weight-bold mr-1">Age:</h6>
                  <h6>{getAge(customerId?.dob)}</h6>
                </div>
              </div>
              <div>
                <div className="d-flex align-items-center mt-1">
                  <h6 className="font-weight-bold mr-1">Gender:</h6>
                  <h6>{customerId?.isMale ? "Male" : "Female"}</h6>
                </div>
              </div>
            </div>

            <div
              className="d-flex align-items-center justify-content-between p-1"
              style={{ borderBottom: "1px solid black", height: "1.7rem" }}
            >
              <div>
                <div className="d-flex align-items-center mt-1 mr-3">
                  <h6 className="font-weight-bold mr-1">Category:</h6>
                  <h6>{category}</h6>
                </div>
              </div>
              <div className="d-flex align-items-center mt-1">
                <h6 className="font-weight-bold mr-1">Sign and symptoms:</h6>
                <h6>{ssx ? ssx : ""}</h6>
              </div>
            </div>
            <div
              className="d-flex align-items-center  justify-content-between p-1"
              style={{ borderBottom: "1px solid black", height: "1.7rem" }}
            >
              <div className="d-flex align-items-center mt-1">
                <h6 className="font-weight-bold mr-1">Sent out to:</h6>
                <h6>{sentOut?.vendors?.displayname}</h6>
              </div>
            </div>
            <div
              style={{
                background: "black",
                height: "1.4rem",
              }}
              className="d-flex align-items-center justify-content-center"
            ></div>
            <table
              style={{ border: "1px solid black", marginTop: "-0.4rem" }}
              className="w-100"
            >
              <thead>
                <tr>
                  <th className="fw-bold text-center  py-2">SERVICES</th>
                </tr>
              </thead>
              <tbody>
                {outsources?.map((outsource, index) => (
                  <tr style={{ border: "1px solid black" }} key={index}>
                    <td style={{ fontWeight: "bold" }}>
                      {index + 1}.{" "}
                      <strong className="ml-3">{outsource.name}</strong>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="d-flex align-items-center mt-2">
            <h6>Generated by:</h6>
            <h6 className="ml-1 fw-bold" style={{ alignItems: "baseline" }}>
              {fullName(auth?.fullName)}
            </h6>
          </div>
        </MDBCol>
      </MDBRow>
    </div>
  );
};

export default RequestOutSource;
