import Sidebars from "./sidebars";
import {
  Statements,
  Menus,
  Payments,
  Philippines,
  Privileges,
  Denominations,
  Services,
  Suffixes,
  Categories,
  Memberships,
} from "./finance";
import Developer from "./developer";
import {
  MicroscopicInRange,
  MicroscopicResultInWord,
  BacteriaInRange,
  PH,
  Consistency,
  SpecificGravity,
  Transparency,
  ResultInRange,
  ResultInName,
  UrineColors,
  FecalColor,
  Cellcount,
  Diffcount,
  Rci,
  References,
  Templates,
} from "./diagnostics";
import Access from "./access";
import Calendar from "./calendar";
import Policy from "./policy";
import Roles from "./roles";

export {
  Denominations,
  Suffixes,
  Calendar,
  Rci,
  Diffcount,
  Cellcount,
  SpecificGravity,
  Transparency,
  ResultInRange,
  ResultInName,
  UrineColors,
  MicroscopicResultInWord,
  BacteriaInRange,
  PH,
  Consistency,
  Developer,
  Sidebars,
  Services,
  References,
  Templates,
  Categories,
  Memberships,
  Privileges,
  Payments,
  Philippines,
  FecalColor,
  MicroscopicInRange,
  Menus,
  Roles,
  Statements,
  Access,
  Policy,
};
