const Preferences = {
  Child: {
    hct: {
      snug: 0.18, // need blood transfusion
      lo: 0.4,
      hi: 0.5,
      crical: 0.6, // Panic Value
      alert: 0, //
      // crical: 0,
      unit: null,
    },
    hgb: {
      snug: 60,
      lo: 130,
      hi: 170,
      warn: 204,
      alert: 0,
      crical: 0,
      unit: "g/l",
    },
    rbc: {
      snug: 1.98,
      lo: 4.5,
      hi: 5,
      warn: 6.6,
      alert: 0,
      crical: 0,
      unit: "x10<sup>12</sup>/L",
    },
    wbc: {
      snug: 1,
      lo: 5,
      hi: 10,
      warn: 16,
      alert: 0,
      crical: 18,
      unit: "x10 <sup>9</sup>/l",
    },
  },
  Male: {
    hct: {
      snug: 0.18, // need blood transfusion
      lo: 0.4,
      hi: 0.54,
      warn: 0.6, // Panic Value
      alert: 0, //
      crical: 0.65,
      unit: null,
    },
    hgb: {
      snug: 60,
      lo: 130,
      hi: 170,
      warn: 180,
      alert: 0,
      crical: 200,
      unit: "g/l",
    },
    rbc: {
      snug: 1.98,
      lo: 4.7,
      hi: 6.1,
      warn: 6.6,
      alert: 0,
      crical: 7.0,
      unit: "x10<sup>12</sup>/L",
    },
    wbc: {
      snug: 1,
      lo: 4.5,
      hi: 11,
      warn: 15,
      alert: 0,
      crical: 20,
      unit: "x10 <sup>9</sup>/l",
    },
  },
  Female: {
    hct: {
      snug: 0.18,
      lo: 0.36,
      hi: 0.48,
      warn: 0,
      alert: 0,
      crical: 0.6,
      unit: null,
    },
    hgb: {
      snug: 60,
      lo: 120,
      hi: 160,
      crical: 204,
      alert: 0,
      unit: "g/l",
    },
    rbc: {
      snug: 1.98,
      lo: 4.2,
      hi: 5.4,
      warn: 6.0,
      alert: 0,
      crical: 6.8,
      unit: "x10 <sup>12</sup>/L",
    },
    wbc: {
      snug: 1,
      lo: 4.5,
      hi: 11,
      warn: 15,
      alert: 18,
      crical: 25,
      unit: "x10 <sup>9</sup>/l",
    },
  },
  plt: { snug: 100, lo: 150, hi: 450, warn: 600, alert: 800, crical: 1000 },
  differentials: {
    Segmenters: { snug: 20, lo: 55, hi: 65, warn: 700, alert: 100, crical: 80 },
    Lymphocytes: {
      snug: 20,
      lo: 25,
      hi: 35,
      warn: 700,
      alert: 100,
      crical: 50,
    },
    Monocytes: { lo: 2, hi: 6, warn: 700, alert: 100, crical: 20 },
    Eosinophils: { lo: 2, hi: 4, warn: 700, alert: 100, crical: 20 },
    Stabs: { lo: 0, hi: 5, warn: 10, alert: 15, crical: 20 },
    Basophils: { lo: 2, hi: 6, warn: 5, alert: 15, crical: 20 },
  },
  rci: {
    MCV: {
      snug: 0,
      lo: 76,
      hi: 96,
      warn: 5,
      alert: 15,
      crical: 20,
      unit: "fl",
    },
    MCH: {
      snug: 0,
      lo: 27,
      hi: 32,
      warn: 5,
      alert: 15,
      crical: 20,
      unit: "pg",
    },
    MCHC: {
      snug: 0,
      lo: 300,
      hi: 350,
      warn: 5,
      alert: 15,
      crical: 20,
      unit: "g/l",
    },
    RDWc: {
      snug: 0,
      lo: 11.0,
      hi: 15.0,
      warn: 5,
      alert: 15,
      crical: 20,
      unit: "%",
    },
  },
};

export default Preferences;
