import { Schedule, Attendances, Calender, Scheduler } from "./dtr";
export { default as Applicants } from "./applicants";
export { default as Equipments } from "../headquarter/file201/equipments";
export { default as Heads } from "../headquarter/personnel/heads";
export { default as Physicians } from "../headquarter/personnel/physicians";
export { default as Procurments } from "../headquarter/file201/procurments";
export { default as Employees } from "../headquarter/file201/employees";
export { default as Hmo } from "../headquarter/file201/hmo";
export { default as Records } from "../headquarter/personnel/records";
export { default as Staffs } from "./staffs";
export { Schedule, Attendances, Calender, Scheduler };
