import Defibrillator from "./../../../../../assets/subscriber/Defibrillator.jpg";
import UM from "./../../../../../assets/subscriber/UM.jpg";
import Ventilator from "./../../../../../assets/subscriber/Ventilator.jpg";
import Electrocardiogram from "./../../../../../assets/subscriber/Electrocardiogram.jpg";
import MRI from "./../../../../../assets/subscriber/MRI.jpg";

const imgs = [Electrocardiogram, Ventilator, UM, MRI, Defibrillator];

const collections = [
  {
    id: 1,
    title: "Item 1 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 1.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Portable and lightweight",
        "Audible voice prompts",
        "Shock delivery up to 200J",
      ],
    },
  },
  {
    id: 2,
    title: "Item 2 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 2.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Dual-head chest piece",
        "High acoustic sensitivity",
        "Comfortable ear tips",
      ],
    },
  },
  {
    id: 3,
    title: "Item 3 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 3.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "One-second measurement",
        "Backlit digital display",
        "Memory for 20 readings",
      ],
    },
  },
  {
    id: 4,
    title: "Item 4 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 4.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Sterile single-use design",
        "Clear volume markings",
        "Smooth plunger action",
      ],
    },
  },
  {
    id: 5,
    title: "Item 5 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 5.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "High-purity oxygen",
        "Adjustable flow regulator",
        "Durable steel cylinder",
      ],
    },
  },
  {
    id: 6,
    title: "Item 6 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 6.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Large digital screen",
        "One-touch operation",
        "Stores last 60 readings",
      ],
    },
  },
  {
    id: 7,
    title: "Item 7 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 7.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "12-lead ECG support",
        "Rechargeable battery",
        "USB data export",
      ],
    },
  },
  {
    id: 8,
    title: "Item 8 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 8.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Quiet ultrasonic operation",
        "Compact and portable",
        "Adjustable mist output",
      ],
    },
  },
  {
    id: 9,
    title: "Item 9 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 9.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Lightweight aluminum frame",
        "Foldable for storage",
        "Detachable footrests",
      ],
    },
  },
  {
    id: 10,
    title: "Item 10 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 10.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Height-adjustable pole",
        "Sturdy stainless steel",
        "Smooth-rolling wheels",
      ],
    },
  },
  {
    id: 11,
    title: "Item 11 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 11.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Portable and lightweight",
        "Audible voice prompts",
        "Shock delivery up to 200J",
      ],
    },
  },
  {
    id: 12,
    title: "Item 12 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 12.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Dual-head chest piece",
        "High acoustic sensitivity",
        "Comfortable ear tips",
      ],
    },
  },
  {
    id: 13,
    title: "Item 13 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 13.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "One-second measurement",
        "Backlit digital display",
        "Memory for 20 readings",
      ],
    },
  },
  {
    id: 14,
    title: "Item 14 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 14.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Sterile single-use design",
        "Clear volume markings",
        "Smooth plunger action",
      ],
    },
  },
  {
    id: 15,
    title: "Item 15 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 15.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "High-purity oxygen",
        "Adjustable flow regulator",
        "Durable steel cylinder",
      ],
    },
  },
  {
    id: 16,
    title: "Item 16 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 16.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Large digital screen",
        "One-touch operation",
        "Stores last 60 readings",
      ],
    },
  },
  {
    id: 17,
    title: "Item 17 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 17.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "12-lead ECG support",
        "Rechargeable battery",
        "USB data export",
      ],
    },
  },
  {
    id: 18,
    title: "Item 18 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 18.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Quiet ultrasonic operation",
        "Compact and portable",
        "Adjustable mist output",
      ],
    },
  },
  {
    id: 19,
    title: "Item 19 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 19.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Lightweight aluminum frame",
        "Foldable for storage",
        "Detachable footrests",
      ],
    },
  },
  {
    id: 20,
    title: "Item 20 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 20.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Height-adjustable pole",
        "Sturdy stainless steel",
        "Smooth-rolling wheels",
      ],
    },
  },
  {
    id: 21,
    title: "Item 21 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 21.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Portable and lightweight",
        "Audible voice prompts",
        "Shock delivery up to 200J",
      ],
    },
  },
  {
    id: 22,
    title: "Item 22 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 22.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Dual-head chest piece",
        "High acoustic sensitivity",
        "Comfortable ear tips",
      ],
    },
  },
  {
    id: 23,
    title: "Item 23 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 23.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "One-second measurement",
        "Backlit digital display",
        "Memory for 20 readings",
      ],
    },
  },
  {
    id: 24,
    title: "Item 24 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 24.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Sterile single-use design",
        "Clear volume markings",
        "Smooth plunger action",
      ],
    },
  },
  {
    id: 25,
    title: "Item 25 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 25.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "High-purity oxygen",
        "Adjustable flow regulator",
        "Durable steel cylinder",
      ],
    },
  },
  {
    id: 26,
    title: "Item 26 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 26.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Large digital screen",
        "One-touch operation",
        "Stores last 60 readings",
      ],
    },
  },
  {
    id: 27,
    title: "Item 27 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 27.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "12-lead ECG support",
        "Rechargeable battery",
        "USB data export",
      ],
    },
  },
  {
    id: 28,
    title: "Item 28 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 28.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Quiet ultrasonic operation",
        "Compact and portable",
        "Adjustable mist output",
      ],
    },
  },
  {
    id: 29,
    title: "Item 29 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 29.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Lightweight aluminum frame",
        "Foldable for storage",
        "Detachable footrests",
      ],
    },
  },
  {
    id: 30,
    title: "Item 30 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 30.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Height-adjustable pole",
        "Sturdy stainless steel",
        "Smooth-rolling wheels",
      ],
    },
  },
  {
    id: 31,
    title: "Item 31 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 31.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Portable and lightweight",
        "Audible voice prompts",
        "Shock delivery up to 200J",
      ],
    },
  },
  {
    id: 32,
    title: "Item 32 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 32.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Dual-head chest piece",
        "High acoustic sensitivity",
        "Comfortable ear tips",
      ],
    },
  },
  {
    id: 33,
    title: "Item 33 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 33.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "One-second measurement",
        "Backlit digital display",
        "Memory for 20 readings",
      ],
    },
  },
  {
    id: 34,
    title: "Item 34 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 34.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Sterile single-use design",
        "Clear volume markings",
        "Smooth plunger action",
      ],
    },
  },
  {
    id: 35,
    title: "Item 35 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 35.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "High-purity oxygen",
        "Adjustable flow regulator",
        "Durable steel cylinder",
      ],
    },
  },
  {
    id: 36,
    title: "Item 36 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 36.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Large digital screen",
        "One-touch operation",
        "Stores last 60 readings",
      ],
    },
  },
  {
    id: 37,
    title: "Item 37 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 37.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "12-lead ECG support",
        "Rechargeable battery",
        "USB data export",
      ],
    },
  },
  {
    id: 38,
    title: "Item 38 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 38.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Quiet ultrasonic operation",
        "Compact and portable",
        "Adjustable mist output",
      ],
    },
  },
  {
    id: 39,
    title: "Item 39 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 39.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Lightweight aluminum frame",
        "Foldable for storage",
        "Detachable footrests",
      ],
    },
  },
  {
    id: 40,
    title: "Item 40 Title",
    price: 100,
    discount: "10% off",
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Description for item 40.",
    color: ["White"],
    size: ["Standard"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 100,
    specifications: {
      weight: "1 kg",
      dimensions: "10 × 10 × 10 cm",
      warranty: "1 year",
      features: [
        "Height-adjustable pole",
        "Sturdy stainless steel",
        "Smooth-rolling wheels",
      ],
    },
  },
];

export default collections;
