import Defibrillator from "./../../../../../assets/subscriber/Defibrillator.jpg";
import UM from "./../../../../../assets/subscriber/UM.jpg";
import Ventilator from "./../../../../../assets/subscriber/Ventilator.jpg";
import Electrocardiogram from "./../../../../../assets/subscriber/Electrocardiogram.jpg";
import MRI from "./../../../../../assets/subscriber/MRI.jpg";

const imgs = [Electrocardiogram, Ventilator, UM, MRI, Defibrillator];

const collections = [
  {
    id: 1,
    title: "Cardiac Defibrillator AED Portable Unit",
    price: 1000,
    discount: 0,
    rating: 4.9,
    sold: 10000,
    image: imgs,
    description:
      "A portable automated external defibrillator that provides a shock to restore normal heart rhythm.",
    color: ["White", "Gray"],
    size: ["Compact", "Standard"],
    capacity: "Up to 200 shocks per charge",
    power: ["Battery-powered", "AC-powered"],
    stock: 50,
    specifications: {
      weight: "2.5 kg",
      dimensions: "20 × 25 × 8 cm",
      warranty: "2 years",
    },
  },
  {
    id: 2,
    title: "Classic Dual-Head Professional Stethoscope",
    price: 150,
    discount: 20,
    rating: 4.8,
    sold: 5000,
    image: imgs,
    description:
      "A premium dual-head stethoscope for listening to heart, lung, and body sounds.",
    color: ["Black", "Blue", "Red"],
    size: ["Standard", "Long Tube"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 120,
    specifications: {
      weight: "150 g",
      dimensions: "90 × 5 × 3 cm",
      warranty: "1 year",
    },
  },
  {
    id: 3,
    title: "Digital Infrared Non-Contact Thermometer",
    price: 50,
    discount: 15,
    rating: 4.7,
    sold: 8000,
    image: imgs,
    description:
      "A non-contact infrared thermometer for quick and accurate temperature readings.",
    color: ["White", "Pink"],
    size: ["Handheld"],
    capacity: "N/A",
    power: ["Battery-powered"],
    stock: 200,
    specifications: {
      weight: "100 g",
      dimensions: "15 × 3 × 1.5 cm",
      warranty: "1 year",
    },
  },
  {
    id: 4,
    title: "Sterile Disposable Syringe 5 mL or 10 mL",
    price: 10,
    discount: 10,
    rating: 4.6,
    sold: 12000,
    image: imgs,
    description: "Sterile disposable syringe for injections or fluid sampling.",
    color: ["Transparent"],
    size: ["5 mL", "10 mL"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 5000,
    specifications: {
      weight: "10 g",
      dimensions: "12 × 1.2 × 1.2 cm",
      warranty: "N/A",
    },
  },
  {
    id: 5,
    title: "Medical Oxygen Cylinder with Regulator (5 L)",
    price: 500,
    discount: 25,
    rating: 4.9,
    sold: 2000,
    image: imgs,
    description:
      "5‑liter medical‑grade oxygen cylinder with adjustable regulator valve.",
    color: ["Green"],
    size: ["5 L", "10 L"],
    capacity: "5 L",
    power: ["Compressed Gas"],
    stock: 80,
    specifications: {
      weight: "3 kg",
      dimensions: "55 × 15 × 15 cm",
      warranty: "2 years",
    },
  },
  {
    id: 6,
    title: "Digital Upper Arm Blood Pressure Monitor",
    price: 120,
    discount: 30,
    rating: 4.8,
    sold: 3000,
    image: imgs,
    description:
      "Automatic upper-arm blood pressure monitor with digital display.",
    color: ["White", "Blue"],
    size: ["Standard cuff", "Large cuff"],
    capacity: "N/A",
    power: ["Battery-powered", "USB-powered"],
    stock: 300,
    specifications: {
      weight: "350 g",
      dimensions: "14 × 10 × 7 cm",
      warranty: "1 year",
    },
  },
  {
    id: 7,
    title: "Automated 12‑Lead ECG Machine Portable",
    price: 1500,
    discount: 40,
    rating: 4.9,
    sold: 1000,
    image: imgs,
    description:
      "Portable 12‑lead electrocardiogram machine with automated analysis features.",
    color: ["White", "Silver"],
    size: ["Compact", "Cart-mounted"],
    capacity: "Supports adult & pediatric",
    power: ["Battery-powered", "AC-powered"],
    stock: 30,
    specifications: {
      weight: "4 kg",
      dimensions: "30 × 25 × 10 cm",
      warranty: "2 years",
    },
  },
  {
    id: 8,
    title: "Ultrasonic Nebulizer Aerosol Therapy Device",
    price: 200,
    discount: 18,
    rating: 4.7,
    sold: 6000,
    image: imgs,
    description:
      "Ultrasonic nebulizer for delivering medication as a fine mist to the lungs.",
    color: ["Blue", "White"],
    size: ["Compact", "Table-top"],
    capacity: "Up to 8 mL reservoir",
    power: ["AC-powered", "Battery-powered"],
    stock: 400,
    specifications: {
      weight: "600 g",
      dimensions: "18 × 15 × 10 cm",
      warranty: "1 year",
    },
  },
  {
    id: 9,
    title: "Lightweight Folding Manual Wheelchair",
    price: 300,
    discount: 22,
    rating: 4.8,
    sold: 4000,
    image: imgs,
    description:
      "Portable, foldable manual wheelchair made of lightweight aluminum.",
    color: ["Black", "Blue"],
    size: ["Standard", "Wide seat"],
    capacity: "Max load 120 kg",
    power: ["Manual"],
    stock: 150,
    specifications: {
      weight: "14 kg",
      dimensions: "100 × 60 × 90 cm",
      warranty: "1 year",
    },
  },
  {
    id: 10,
    title: "Adjustable Stainless Steel IV Stand with Wheels",
    price: 80,
    discount: 12,
    rating: 4.6,
    sold: 7000,
    image: imgs,
    description:
      "Adjustable stainless-steel IV stand featuring rolling wheels and height lock.",
    color: ["Silver"],
    size: ["Medium", "Tall"],
    capacity: "Holds multiple IV bags",
    power: ["Manual"],
    stock: 250,
    specifications: {
      weight: "5 kg",
      dimensions: "160–180 cm height",
      warranty: "2 years",
    },
  },
  {
    id: 11,
    title: "Disposable Surgical Face Mask (Box of 50)",
    price: 20,
    discount: 50,
    rating: 4.7,
    sold: 50000,
    image: imgs,
    description:
      "Box of 50 disposable surgical masks for infection protection.",
    color: ["Blue", "White"],
    size: ["Adult", "Kids"],
    capacity: "50 pieces per box",
    power: ["Manual"],
    stock: 15000,
    specifications: {
      weight: "200 g",
      dimensions: "20 × 10 × 5 cm",
      warranty: "N/A",
    },
  },
  {
    id: 12,
    title: "Powder-Free Latex Examination Gloves (Box 100)",
    price: 15,
    discount: 40,
    rating: 4.8,
    sold: 35000,
    image: imgs,
    description: "Box of 100 powder-free latex gloves for medical examination.",
    color: ["White"],
    size: ["Small", "Medium", "Large"],
    capacity: "100 pieces per box",
    power: ["Manual"],
    stock: 12000,
    specifications: {
      weight: "250 g",
      dimensions: "25 × 20 × 3 cm",
      warranty: "N/A",
    },
  },
  {
    id: 13,
    title: "Elastic Medical Bandage Roll (5 cm × 4 m)",
    price: 5,
    discount: 25,
    rating: 4.5,
    sold: 20000,
    image: imgs,
    description: "Elastic bandage roll for wound dressing and compression.",
    color: ["White", "Skin tone"],
    size: ["5 cm × 4 m", "10 cm × 4 m"],
    capacity: "Single roll",
    power: ["Manual"],
    stock: 8000,
    specifications: {
      weight: "30 g",
      dimensions: "5 × 4 m roll",
      warranty: "N/A",
    },
  },
  {
    id: 14,
    title: "Handheld Pulse Oximeter Fingertip",
    price: 60,
    discount: 30,
    rating: 4.8,
    sold: 9000,
    image: imgs,
    description:
      "Fingertip pulse oximeter measures blood oxygen saturation and pulse rate.",
    color: ["Black", "Pink", "White"],
    size: ["Finger tip"],
    capacity: "N/A",
    power: ["Battery-powered"],
    stock: 6000,
    specifications: {
      weight: "50 g",
      dimensions: "6 × 3 × 3 cm",
      warranty: "1 year",
    },
  },
  {
    id: 15,
    title: "Precision Surgical Scalpel Stainless Steel",
    price: 25,
    discount: 15,
    rating: 4.6,
    sold: 3000,
    image: imgs,
    description:
      "High-precision sterile surgical scalpel with stainless steel blade.",
    color: ["Silver"],
    size: ["10 cm blade"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 1500,
    specifications: {
      weight: "20 g",
      dimensions: "15 × 1 × 0.5 cm",
      warranty: "N/A",
    },
  },
  {
    id: 16,
    title: "Adjustable Aluminum Crutches Pair",
    price: 90,
    discount: 20,
    rating: 4.7,
    sold: 2000,
    image: imgs,
    description:
      "Adjustable height aluminum crutches with comfortable hand grips.",
    color: ["Silver", "Blue"],
    size: ["Adult", "Child"],
    capacity: "User weight up to 120 kg",
    power: ["Manual"],
    stock: 200,
    specifications: {
      weight: "1.2 kg (pair)",
      dimensions: "Adjustable 100–140 cm",
      warranty: "1 year",
    },
  },
  {
    id: 17,
    title: "Dental Examination Mirror with Handle",
    price: 30,
    discount: 18,
    rating: 4.5,
    sold: 1000,
    image: imgs,
    description: "Stainless steel dental mirror for oral examination.",
    color: ["Silver"],
    size: ["Mirror Ø 2 cm"],
    capacity: "Single piece",
    power: ["Manual"],
    stock: 900,
    specifications: {
      weight: "30 g",
      dimensions: "Mirror Ø 2 cm, handle 15 cm",
      warranty: "N/A",
    },
  },
  {
    id: 18,
    title: "Stainless Steel Surgical Forceps Curved",
    price: 40,
    discount: 22,
    rating: 4.6,
    sold: 1500,
    image: imgs,
    description: "Curved surgical forceps made of sterile stainless steel.",
    color: ["Silver"],
    size: ["15 cm", "18 cm"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 1400,
    specifications: {
      weight: "50 g",
      dimensions: "Length 15–18 cm",
      warranty: "N/A",
    },
  },
  {
    id: 19,
    title: "Complete First Aid Kit Medical Grade",
    price: 70,
    discount: 35,
    rating: 4.9,
    sold: 8000,
    image: imgs,
    description:
      "Comprehensive first aid kit containing bandages, antiseptics, scissors & more.",
    color: ["Red", "White"],
    size: ["Standard kit"],
    capacity: "Up to 50 uses",
    power: ["Manual"],
    stock: 500,
    specifications: {
      weight: "1.2 kg",
      dimensions: "30 × 20 × 10 cm",
      warranty: "6 months",
    },
  },
  {
    id: 20,
    title: "Medical Grade Scissors Surgical Shears",
    price: 18,
    discount: 12,
    rating: 4.7,
    sold: 6000,
    image: imgs,
    description: "Stainless steel surgical scissors for medical use.",
    color: ["Silver"],
    size: ["Straight 15 cm", "Curved 15 cm"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 6000,
    specifications: {
      weight: "40 g",
      dimensions: "Length 15 cm",
      warranty: "N/A",
    },
  },
  {
    id: 21,
    title: "Sterile Surgical Gown Disposable",
    price: 45,
    discount: 28,
    rating: 4.7,
    sold: 4000,
    image: imgs,
    description:
      "Sterile disposable surgical gown made from breathable material.",
    color: ["Blue", "Green"],
    size: ["Small", "Medium", "Large"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 3500,
    specifications: {
      weight: "200 g",
      dimensions: "Medium size",
      warranty: "N/A",
    },
  },
  {
    id: 22,
    title: "Full Face Shield Protective Visor",
    price: 10,
    discount: 50,
    rating: 4.6,
    sold: 15000,
    image: imgs,
    description:
      "Clear full-face shield visor for splash and droplet protection.",
    color: ["Transparent"],
    size: ["Universal Fit"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 15000,
    specifications: {
      weight: "50 g",
      dimensions: "30 × 22 cm",
      warranty: "N/A",
    },
  },
  {
    id: 23,
    title: "Heavy-Duty Hospital Bed Adjustable with Rails",
    price: 2500,
    discount: 20,
    rating: 4.9,
    sold: 500,
    image: imgs,
    description:
      "Adjustable hospital bed with side rails and electronic controls.",
    color: ["White"],
    size: ["Single", "Double"],
    capacity: "Weight Capacity 200 kg",
    power: ["AC-powered", "Battery backup"],
    stock: 80,
    specifications: {
      weight: "75 kg",
      dimensions: "200 × 100 × 50 cm",
      warranty: "3 years",
    },
  },
  {
    id: 24,
    title: "Portable Suction Machine Electric",
    price: 800,
    discount: 30,
    rating: 4.8,
    sold: 700,
    image: imgs,
    description:
      "Portable suction device for airway clearance and surgical procedures.",
    color: ["White", "Blue"],
    size: ["Hand-carried", "Cart-mounted"],
    capacity: "Max flow 20 L/min",
    power: ["Battery-powered", "AC-powered"],
    stock: 120,
    specifications: {
      weight: "6 kg",
      dimensions: "35 × 25 × 20 cm",
      warranty: "2 years",
    },
  },
  {
    id: 25,
    title: "Infusion Pump Volumetric with Safety Alarms",
    price: 1100,
    discount: 25,
    rating: 4.8,
    sold: 600,
    image: imgs,
    description:
      "Volumetric infusion pump delivering precise IV fluids with safety alarms.",
    color: ["White", "Gray"],
    size: ["Bedside", "Cart-mounted"],
    capacity: "Infusion rate 1–1200 mL/hr",
    power: ["Battery-powered", "AC-powered"],
    stock: 90,
    specifications: {
      weight: "5 kg",
      dimensions: "28 × 22 × 15 cm",
      warranty: "2 years",
    },
  },
  {
    id: 26,
    title: "Infrared Thermal Scanner Infrared Gun",
    price: 75,
    discount: 15,
    rating: 4.6,
    sold: 5000,
    image: imgs,
    description:
      "Handheld infrared thermal scanner for quick body temperature screening.",
    color: ["Black", "White"],
    size: ["Pistol-grip"],
    capacity: "N/A",
    power: ["Battery-powered", "Rechargeable"],
    stock: 1800,
    specifications: {
      weight: "200 g",
      dimensions: "15 × 10 × 5 cm",
      warranty: "1 year",
    },
  },
  {
    id: 27,
    title: "Medical Examination Table Adjustable",
    price: 700,
    discount: 22,
    rating: 4.7,
    sold: 1000,
    image: imgs,
    description:
      "Adjustable examination table with cushioned surface and storage shelf.",
    color: ["White", "Light Gray"],
    size: ["Single‑section", "Two‑section"],
    capacity: "Supports patient weight up to 180 kg",
    power: ["Manual", "Hydraulic"],
    stock: 120,
    specifications: {
      weight: "40 kg",
      dimensions: "185 × 65 × 75 cm",
      warranty: "2 years",
    },
  },
  {
    id: 28,
    title: "Electric Steam Sterilizer Large Capacity",
    price: 300,
    discount: 18,
    rating: 4.7,
    sold: 3000,
    image: imgs,
    description:
      "Electric steam sterilizer for rapid sterilization of instruments.",
    color: ["White"],
    size: ["Small", "Large"],
    capacity: "Holds up to 6 trays",
    power: ["AC-powered"],
    stock: 250,
    specifications: {
      weight: "10 kg",
      dimensions: "40 × 30 × 30 cm",
      warranty: "2 years",
    },
  },
  {
    id: 29,
    title: "Defibrillator Replacement Pads Adult & Pediatric",
    price: 50,
    discount: 12,
    rating: 4.6,
    sold: 4000,
    image: imgs,
    description: "Replacement electrode pads compatible with most AED units.",
    color: ["White"],
    size: ["Adult", "Pediatric"],
    capacity: "Single pair",
    power: ["Manual"],
    stock: 3500,
    specifications: {
      weight: "80 g",
      dimensions: "10 × 8 × 2 cm",
      warranty: "N/A",
    },
  },
  {
    id: 30,
    title: "Stainless Medical Trolley Multi-Tier",
    price: 400,
    discount: 20,
    rating: 4.7,
    sold: 2000,
    image: imgs,
    description:
      "Stainless steel medical trolley with multiple shelves and lockable wheels.",
    color: ["Silver"],
    size: ["Two-tier", "Three-tier"],
    capacity: "Load up to 50 kg",
    power: ["Manual"],
    stock: 500,
    specifications: {
      weight: "12 kg",
      dimensions: "90 × 45 × 90 cm",
      warranty: "2 years",
    },
  },
  {
    id: 31,
    title: "LED Otoscope with 3.5 V Bulb Rechargeable",
    price: 120,
    discount: 25,
    rating: 4.8,
    sold: 1500,
    image: imgs,
    description:
      "LED otoscope for ear examination, rechargeable with 3.5 V bulb.",
    color: ["Black"],
    size: ["Handheld"],
    capacity: "N/A",
    power: ["Rechargeable"],
    stock: 800,
    specifications: {
      weight: "120 g",
      dimensions: "18 × 3 × 3 cm",
      warranty: "1 year",
    },
  },
  {
    id: 32,
    title: "Stainless Steel Vaginal Speculum Disposable",
    price: 35,
    discount: 30,
    rating: 4.5,
    sold: 900,
    image: imgs,
    description:
      "Disposable stainless steel speculum for gynecological examinations.",
    color: ["Silver"],
    size: ["Small", "Medium", "Large"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 700,
    specifications: {
      weight: "60 g",
      dimensions: "Length 12 cm",
      warranty: "N/A",
    },
  },
  {
    id: 33,
    title: "Disposable Surgical Drapes Pack of 10",
    price: 55,
    discount: 22,
    rating: 4.7,
    sold: 2500,
    image: imgs,
    description: "Pack of 10 sterile surgical drapes for operating use.",
    color: ["Blue"],
    size: ["Single‑use"],
    capacity: "10 drapes per pack",
    power: ["Manual"],
    stock: 2200,
    specifications: {
      weight: "500 g",
      dimensions: "Pack 40 × 40 cm",
      warranty: "N/A",
    },
  },
  {
    id: 34,
    title: "Disposable Medical Apron Waterproof",
    price: 25,
    discount: 15,
    rating: 4.6,
    sold: 3500,
    image: imgs,
    description: "Waterproof disposable medical apron for staff protection.",
    color: ["White", "Green"],
    size: ["One size"],
    capacity: "Single use",
    power: ["Manual"],
    stock: 3000,
    specifications: {
      weight: "150 g",
      dimensions: "Length 100 × width 60 cm",
      warranty: "N/A",
    },
  },
  {
    id: 35,
    title: "Sterile IV Cannula Plastic (pack of 50)",
    price: 8,
    discount: 10,
    rating: 4.5,
    sold: 10000,
    image: imgs,
    description: "Box of 50 sterile IV cannulae for intravenous access.",
    color: ["Transparent"],
    size: ["18G", "20G", "22G"],
    capacity: "50 pieces per box",
    power: ["Manual"],
    stock: 8000,
    specifications: {
      weight: "250 g",
      dimensions: "Box 15 × 10 × 5 cm",
      warranty: "N/A",
    },
  },
  {
    id: 36,
    title: "Wooden Tongue Depressor Flat Rounded",
    price: 5,
    discount: 8,
    rating: 4.4,
    sold: 8000,
    image: imgs,
    description: "Pack of wooden tongue depressors for oral examinations.",
    color: ["Natural Wood"],
    size: ["Standard 15 cm"],
    capacity: "50 pieces per pack",
    power: ["Manual"],
    stock: 8000,
    specifications: {
      weight: "200 g",
      dimensions: "Pack 15 × 10 × 2 cm",
      warranty: "N/A",
    },
  },
  {
    id: 37,
    title: "Medical Grade Surgical Tape Roll 3 cm × 10 m",
    price: 12,
    discount: 18,
    rating: 4.6,
    sold: 6000,
    image: imgs,
    description: "Medical-grade adhesive surgical tape for dressing fixation.",
    color: ["White", "Beige"],
    size: ["3 cm × 10 m", "5 cm × 10 m"],
    capacity: "Single roll",
    power: ["Manual"],
    stock: 6000,
    specifications: {
      weight: "50 g",
      dimensions: "Roll 3 × 10 m",
      warranty: "N/A",
    },
  },
  {
    id: 38,
    title: "Heavy-Duty Emergency Stretcher Foldable",
    price: 900,
    discount: 25,
    rating: 4.8,
    sold: 1000,
    image: imgs,
    description:
      "Heavy-duty foldable stretcher for emergency patient transport.",
    color: ["Orange", "Black"],
    size: ["Standard", "Wide"],
    capacity: "Load up to 200 kg",
    power: ["Manual"],
    stock: 400,
    specifications: {
      weight: "15 kg",
      dimensions: "210 × 70 × 20 cm (folded)",
      warranty: "2 years",
    },
  },
  {
    id: 39,
    title: "Analog Sphygmomanometer Blood Pressure Cuff",
    price: 150,
    discount: 30,
    rating: 4.7,
    sold: 2200,
    image: imgs,
    description:
      "Analog sphygmomanometer with cuff and aneroid gauge for blood pressure measurement.",
    color: ["Black"],
    size: ["Adult cuff", "Pediatric cuff"],
    capacity: "N/A",
    power: ["Manual"],
    stock: 1200,
    specifications: {
      weight: "500 g",
      dimensions: "Gauge Ø 6 cm, cuff 30 × 10 cm",
      warranty: "1 year",
    },
  },
  {
    id: 40,
    title: "Overhead Surgical Light LED Ceiling‑Mount",
    price: 3000,
    discount: 20,
    rating: 4.9,
    sold: 400,
    image: imgs,
    description:
      "High-intensity LED surgical overhead light for operating rooms.",
    color: ["White"],
    size: ["Single dome", "Double dome"],
    capacity: "Illuminance up to 160,000 lux",
    power: ["AC-powered"],
    stock: 300,
    specifications: {
      weight: "12 kg",
      dimensions: "Dome Ø 50–70 cm",
      warranty: "3 years",
    },
  },
];

export default collections;
