import Defibrillator from "./../../../../../assets/subscriber/Defibrillator.jpg";
import UM from "./../../../../../assets/subscriber/UM.jpg";
import Ventilator from "./../../../../../assets/subscriber/Ventilator.jpg";
import Electrocardiogram from "./../../../../../assets/subscriber/Electrocardiogram.jpg";
import MRI from "./../../../../../assets/subscriber/MRI.jpg";

const extraImgs = [Electrocardiogram, Ventilator, UM, MRI];

const collections = [
  {
    id: 1,
    title: "Defibrillator adasdasdasdasdasda",
    price: 1000,
    discount: "35% off",
    rating: 4.9,
    sold: 10000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 2,
    title: "Stethoscope",
    price: 150,
    discount: "20% off",
    rating: 4.8,
    sold: 5000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 3,
    title: "Thermometer",
    price: 50,
    discount: "15% off",
    rating: 4.7,
    sold: 8000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 4,
    title: "Syringe",
    price: 10,
    discount: "10% off",
    rating: 4.6,
    sold: 12000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 5,
    title: "Oxygen Tank",
    price: 500,
    discount: "25% off",
    rating: 4.9,
    sold: 2000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 6,
    title: "Blood Pressure Monitor",
    price: 120,
    discount: "30% off",
    rating: 4.8,
    sold: 3000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 7,
    title: "ECG Machine",
    price: 1500,
    discount: "40% off",
    rating: 4.9,
    sold: 1000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 8,
    title: "Nebulizer",
    price: 200,
    discount: "18% off",
    rating: 4.7,
    sold: 6000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 9,
    title: "Wheelchair",
    price: 300,
    discount: "22% off",
    rating: 4.8,
    sold: 4000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 10,
    title: "IV Stand",
    price: 80,
    discount: "12% off",
    rating: 4.6,
    sold: 7000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 11,
    title: "Surgical Mask",
    price: 20,
    discount: "50% off",
    rating: 4.7,
    sold: 50000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 12,
    title: "Gloves",
    price: 15,
    discount: "40% off",
    rating: 4.8,
    sold: 35000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 13,
    title: "Bandage",
    price: 5,
    discount: "25% off",
    rating: 4.5,
    sold: 20000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 14,
    title: "Pulse Oximeter",
    price: 60,
    discount: "30% off",
    rating: 4.8,
    sold: 9000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 15,
    title: "Scalpel",
    price: 25,
    discount: "15% off",
    rating: 4.6,
    sold: 3000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 16,
    title: "Crutches",
    price: 90,
    discount: "20% off",
    rating: 4.7,
    sold: 2000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 17,
    title: "Dental Mirror",
    price: 30,
    discount: "18% off",
    rating: 4.5,
    sold: 1000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 18,
    title: "Forceps",
    price: 40,
    discount: "22% off",
    rating: 4.6,
    sold: 1500,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 19,
    title: "First Aid Kit",
    price: 70,
    discount: "35% off",
    rating: 4.9,
    sold: 8000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 20,
    title: "Medical Scissors",
    price: 18,
    discount: "12% off",
    rating: 4.7,
    sold: 6000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 21,
    title: "Surgical Gown",
    price: 45,
    discount: "28% off",
    rating: 4.7,
    sold: 4000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 22,
    title: "Face Shield",
    price: 10,
    discount: "50% off",
    rating: 4.6,
    sold: 15000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 23,
    title: "Hospital Bed",
    price: 2500,
    discount: "20% off",
    rating: 4.9,
    sold: 500,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 24,
    title: "Suction Machine",
    price: 800,
    discount: "30% off",
    rating: 4.8,
    sold: 700,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 25,
    title: "Infusion Pump",
    price: 1100,
    discount: "25% off",
    rating: 4.8,
    sold: 600,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 26,
    title: "Thermal Scanner",
    price: 75,
    discount: "15% off",
    rating: 4.6,
    sold: 5000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 27,
    title: "Exam Table",
    price: 700,
    discount: "22% off",
    rating: 4.7,
    sold: 1000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 28,
    title: "Sterilizer",
    price: 300,
    discount: "18% off",
    rating: 4.7,
    sold: 3000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 29,
    title: "Defibrillator Pads",
    price: 50,
    discount: "12% off",
    rating: 4.6,
    sold: 4000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 30,
    title: "Medical Trolley",
    price: 400,
    discount: "20% off",
    rating: 4.7,
    sold: 2000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 31,
    title: "Otoscope",
    price: 120,
    discount: "25% off",
    rating: 4.8,
    sold: 1500,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 32,
    title: "Speculum",
    price: 35,
    discount: "30% off",
    rating: 4.5,
    sold: 900,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 33,
    title: "Surgical Drapes",
    price: 55,
    discount: "22% off",
    rating: 4.7,
    sold: 2500,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 34,
    title: "Medical Apron",
    price: 25,
    discount: "15% off",
    rating: 4.6,
    sold: 3500,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 35,
    title: "IV Cannula",
    price: 8,
    discount: "10% off",
    rating: 4.5,
    sold: 10000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 36,
    title: "Tongue Depressor",
    price: 5,
    discount: "8% off",
    rating: 4.4,
    sold: 8000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 37,
    title: "Surgical Tape",
    price: 12,
    discount: "18% off",
    rating: 4.6,
    sold: 6000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 38,
    title: "Stretcher",
    price: 900,
    discount: "25% off",
    rating: 4.8,
    sold: 1000,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 39,
    title: "Sphygmomanometer",
    price: 150,
    discount: "30% off",
    rating: 4.7,
    sold: 2200,
    image: Defibrillator,
    extraImages: extraImgs,
  },
  {
    id: 40,
    title: "Surgical Light",
    price: 3000,
    discount: "20% off",
    rating: 4.9,
    sold: 400,
    image: Defibrillator,
    extraImages: extraImgs,
  },
];

export default collections;
