import Bulletin from "../../../pages/platforms/cashier/bulletin";
import {
  Cashier,
  Contract,
  Deals,
  Menus,
  Services,
  Membership,
  Outsources,
  Utilities,
  Wellness,
  Referrals,
  HMO,
  Remittances,
  Hotlines,
  Suppliers,
  Payables,
  Receivables,
  Vouchers,
  Payments,
  SOA,
  Reseco,
  Onboarding,
} from "../../../pages/platforms/cashier";
import StaffSchedule from "../../../pages/platforms/cashier/scheduler";

const cashier = [
  {
    name: "Bulletin",
    icon: "bullhorn",
    path: "/bulletin",
    title: "News and Updates",
    component: Bulletin,
  },
  {
    name: "Cash Register",
    path: "/cash/register",
    icon: "cash-register",
    title: "Cash Register Functions",
    children: [
      {
        name: "POS",
        path: "/pos",
        icon: "shopping-cart",
        title: "Point of Sales",
        component: Cashier,
      },
      {
        name: "Deals",
        path: "/deals",
        icon: "tags",
        title: "Service Deals of the Day",
        component: Deals,
      },
      {
        name: "Remittances",
        path: "/remittances",
        icon: "exchange-alt",
        title: "Daily Remittance Ledger",
        component: Remittances,
      },
      {
        name: "Onboarding",
        path: "/onboarding",
        icon: "user-plus",
        title: "Insourcing Onboarding",
        component: Onboarding,
      },
    ],
  },
  {
    name: "Accrued",
    path: "/accrued",
    icon: "file-invoice",
    title: "Liabilities and Obligations",
    children: [
      {
        name: "Accounts Payable (A/P)",
        path: "/payables",
        icon: "file-invoice-dollar",
        title: "Outstanding Payments to Suppliers & Utilities",
        component: Payables,
      },
      {
        name: "Payments",
        path: "/payments",
        icon: "money-check-alt",
        title: "List of Payments Made",
        component: Payments,
      },
      {
        name: "Statement of Account (SOA)",
        path: "/soa",
        icon: "file-contract",
        title: "Outsourced Services from Monthly Sales",
        component: SOA,
      },
      {
        name: "Accounts Receivable (A/R)",
        path: "/receivables",
        icon: "wallet",
        title: "Unpaid Corporate & HMO Invoices",
        component: Receivables,
      },
      {
        name: "Vouchers",
        path: "/vouchers",
        icon: "receipt",
        title: "Vouchers from Daily Sales",
        component: Vouchers,
      },
      {
        name: "Reseco",
        path: "/reseco",
        icon: "calendar-check",
        title: "Monthly Reseco Deals",
        component: Reseco,
      },
    ],
  },
  {
    name: "Sources",
    path: "/sources",
    icon: "building",
    title: "Outsources & Insources",
    children: [
      {
        name: "Outsources",
        path: "/outsources",
        icon: "people-carry",
        title: "External Service Providers",
        component: Outsources,
      },
      {
        name: "Insources",
        path: "/insources",
        icon: "user-friends",
        title: "Service Senders",
        children: [
          {
            name: "Wellness",
            path: "/wellness",
            icon: "heartbeat",
            title: "Companies with Wellness Packages",
            component: Wellness,
          },
          {
            name: "Membership",
            path: "/membership",
            icon: "id-card",
            title: "Employee Senders",
            component: Membership,
          },
          {
            name: "Contract",
            path: "/contract",
            icon: "file-signature",
            title: "Laboratory Contract Providers",
            component: Contract,
          },
          {
            name: "Referrals",
            path: "/referrals",
            icon: "paper-plane",
            title: "Medical Referral Sources",
            component: Referrals,
          },
        ],
      },
      {
        name: "HMO",
        path: "/hmo",
        icon: "user-md",
        title: "Companies with HMO",
        component: HMO,
      },
      {
        name: "Suppliers",
        path: "/suppliers",
        icon: "boxes",
        title: "Suppliers for Goods & Services",
        component: Suppliers,
      },
      {
        name: "Utilities",
        path: "/utilities",
        icon: "plug",
        title: "Utilities & Support Services",
        component: Utilities,
      },
      {
        name: "Hotlines",
        path: "/hotlines",
        icon: "phone-alt",
        title: "Emergency & Support Hotlines",
        component: Hotlines,
      },
    ],
  },
  {
    name: "Services Catalog",
    path: "/catalogs",
    icon: "clipboard-list",
    title: "Service Listings",
    children: [
      {
        name: "Menus",
        path: "/menus",
        icon: "utensils",
        title: "List of Menus",
        component: Menus,
      },
      {
        name: "Services",
        path: "/services",
        icon: "concierge-bell",
        title: "List of Services",
        component: Services,
      },
    ],
  },
  {
    name: "Schedule",
    path: "/schedule",
    icon: "calendar-alt",
    title: "Staff Schedules",
    component: StaffSchedule,
  },
];

export default cashier;
