import { configureStore } from "@reduxjs/toolkit";
import {
  auth,
  personnels,
  users,
  physicians,
  heads,
  applicants,
  companies,
  procurements,
  branches,
  providers,
  tieups,
} from "./slices/assets";
import { dragDrop, table } from "./slices/reusable";
import {
  menus,
  services,
  pos,
  sales,
  taskGenerator,
  deals,
  billings,
  dispenser,
  onBoardings,
  admission,
} from "./slices/commerce";

import {
  hematology,
  urinalysis,
  fecalysis,
  electrolyte,
  serology,
  chemistry,
  preferences,
  validator,
  temperatures,
  controls,
  assurances,
  xray,
  ultrasound,
  ecg,
  miscellaneous,
  appointments,
} from "./slices/diagnostics";

import { access, liabilities } from "./slices/liability";
import {
  remittances,
  payables,
  payments,
  payrolls,
  ledger,
  soa,
  orgChart,
  duties,
} from "./slices/finance";
import { quest } from "./slices/diagnostics";
import {
  products,
  productsGenerics,
  machines,
  medicines,
  generics,
  mentainance,
  attendances,
} from "./slices/market";
import portal from "./slices/emr/portal";

const store = configureStore({
  reducer: {
    duties,
    appointments,
    remittances,
    payables,
    payments,
    payrolls,
    billings,
    auth,
    personnels,
    access,
    users,
    ledger,
    soa,
    preferences,
    validator,
    physicians,
    menus,
    admission,
    services,
    onBoardings,
    sales,
    taskGenerator,
    deals,
    pos,
    dispenser,
    heads,
    tieups,
    chemistry,
    companies,
    procurements,
    branches,
    hematology,
    urinalysis,
    fecalysis,
    applicants,
    liabilities,
    electrolyte,
    serology,
    temperatures,
    providers,
    controls,
    assurances,
    products,
    xray,
    ultrasound,
    ecg,
    productsGenerics,
    machines,
    attendances,
    // temperaturez,
    medicines,
    generics,
    mentainance,
    quest,
    //this is results for viewing the results online
    portal,
    //for templates only
    dragDrop,
    table,
    miscellaneous,
    orgChart,
  },
  devTools: true,
});

export default store;
