export { default as ChemLog } from "./chemistry";
export { default as HemaLog } from "./hematology";
export { default as FecaLog } from "./fecalysis.jsx";
// export { default as Coagulation } from "./coagulation";
// export { default as Miscellaneous } from "./miscellaneous";
// export { default as Analysis } from "./analysis";
// export { default as Bacteriology } from "./bacteriology";
// export { default as Compatibility } from "./compatibility";
// export { default as Pbs } from "./pbs";
export { default as ElecLog } from "./electrolytes.jsx";
export { default as SeroLog } from "./serology";
export { default as UrinLog } from "./urinalysis";
